### ISSUE TITLE
Internal structure of the project

### ISSUE THREAD

**Issue by Pacco1217** [jmmartinez/easy-just-in-time#47]
Hi, I'm actually doing my bachelor's thesis about Just in Time compiler and i found your project, which could be really useful for me. But, I have a question, is there any documentation about the internal structure of the project, or about how the library works ? It could be a mailling list or a schema with explanation or anything else.

**Comment by jmmartinez** [comment]
There is almost no documentation of the internals. Nevertheless, the project remains relatively small and simple, so it should be easy to understand all the concepts behind.

When there is a call to the function "easy::jit" (include/easy/jit.h), a "Context" (easy/runtime/Context.h) is built. This context contains all the information required to use the jit.

Then, the function "Function::Compile" is in charge of using the Context to recover the LLVM representation of the function, and invoke the LLVM Optimizer and Jit to generate the appropriate code.

Hope this helps.

As in the known issues of the current implementation, it has problems when linking statically against LLVM (dynamic linkage must be used). I have a solution in mind on how to solve this, but it requires patching LLVM.

Cheers

**Comment by jmmartinez** [comment]
Sorry, closed by accident.

**Comment by Pacco1217** [comment]
Hi, thank you for your answer. Indeed it helps me.
